# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65228125491801432812838c5fe9d24a7a8b91bd92a02136e9ffda3741898621b1f3731758e8c01f8b15b9c98f75bb50bf50dfac3810c3ded7bed6be93898032

test:
  secret_key_base: 9ec3985a79bb7f974f3e25a04e6eee6ee8c21ef080f975c2efc15e7b411b5d1369cbf2886457e98dba60a2447f30d6b524cdaeca4949d7e288e2535e4973ad76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
